name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
      tokenizers_proto_version:
        required: true
permissions:
  contents: write

jobs:
  pack:
    runs-on: ubuntu-latest
    env:
      NET_RUNTIMES: "linux-musl-arm64 linux-musl-x64 linux-arm64 linux-x64 osx-arm64 osx-x64 win-arm64 win-x64"
      RUST_RUNTIMES: "aarch64-linux-musl x86_64-linux-musl aarch64-linux-gnu x86_64-linux-gnu aarch64-darwin x86_64-darwin aarch64-windows x86_64-windows"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: v${{ inputs.version }}
      - name: set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.428'
      - name: download libraries
        run: |
          read -a net_runtimes <<< "${{ env.NET_RUNTIMES }}"
          read -a rust_runtimes <<< "${{ env.RUST_RUNTIMES }}"
          for ((i=0;i<${#net_runtimes[@]};i++))
          do
            mkdir -p ./runtimes/${net_runtimes[i]}/native
            curl -L "https://github.com/IgnaciodelaTorreArias/tokenizers_proto/releases/download/v${{ inputs.tokenizers_proto_version }}/${rust_runtimes[i]}.tar.gz" |
            tar -xzf - -C ./runtimes/${net_runtimes[i]}/native
          done
      - name: run dotnet pack
        run: dotnet pack Tokenizers.HuggingFace.csproj -c Release -p:PackageVersion=${{ inputs.version }}
      - name: publish to nuget
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      - name: upload .nupkg
        uses: actions/upload-artifact@v4
        with:
          name: Tokenizers.HuggingFace
          path: bin/Release/*.nupkg
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ inputs.version }}
          tag_name: v${{ inputs.version }}
          draft: false
          files: |
            bin/Release/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
