name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
      tokenizers_proto_version:
        required: true
permissions:
  contents: write

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: v${{ inputs.version }}
      - name: set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.428'
      # Start downloads
      - run: sudo apt install -y unzip
      - name: linux-arm64
        run : |
          curl -LO "https://github.com/IgnaciodelaTorreArias/tokenizers_proto/releases/download/v${{ inputs.tokenizers_proto_version }}/linux-arm64.zip"
          unzip "linux-arm64.zip" -d runtimes/linux-arm64/native
      - name: linux-x64
        run : |
          curl -LO "https://github.com/IgnaciodelaTorreArias/tokenizers_proto/releases/download/v${{ inputs.tokenizers_proto_version }}/linux-x64.zip"
          unzip "linux-x64.zip" -d runtimes/linux-x64/native
      - name: osx-arm64
        run : |
          curl -LO "https://github.com/IgnaciodelaTorreArias/tokenizers_proto/releases/download/v${{ inputs.tokenizers_proto_version }}/darwin-arm64.zip"
          unzip "darwin-arm64.zip" -d runtimes/osx-arm64/native
      - name: osx-x64
        run : |
          curl -LO "https://github.com/IgnaciodelaTorreArias/tokenizers_proto/releases/download/v${{ inputs.tokenizers_proto_version }}/darwin-x64.zip"
          unzip "darwin-x64.zip" -d runtimes/osx-x64/native
      - name: win-arm64
        run : |
          curl -LO "https://github.com/IgnaciodelaTorreArias/tokenizers_proto/releases/download/v${{ inputs.tokenizers_proto_version }}/windows-arm64.zip"
          unzip "windows-arm64.zip" -d runtimes/win-arm64/native
      - name: win-x64
        run : |
          curl -LO "https://github.com/IgnaciodelaTorreArias/tokenizers_proto/releases/download/v${{ inputs.tokenizers_proto_version }}/windows-x64.zip"
          unzip "windows-x64.zip" -d runtimes/win-x64/native
      # Finish downloads
      - name: run dotnet pack
        run: dotnet pack Tokenizers.HuggingFace.csproj -c Release -p:PackageVersion=${{ inputs.version }}
      - name: publish to nuget
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      - name: upload .nupkg
        uses: actions/upload-artifact@v4
        with:
          name: Tokenizers.HuggingFace
          path: bin/Release/*.nupkg
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release v${{ inputs.version }}
          tag_name: v${{ inputs.version }}
          draft: false
          files: |
            bin/Release/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
